### ISSUE TITLE
HDF5 file size never decreases + concurrent interpreters can overwrite each others files.

### ISSUE THREAD

**Issue by root-11** [root-11/tablite#61]
Problems:

1. A report made clear that the HDF5 size does not decrease. HDF5 confirms this: The blocks on the file system remain reserved. Compressing the file using HDF5 tools results in a full copy of the remaining dataset. Due to the amount of wip-data that some tablite users face, compressing isn't acceptable.
2. Another report made clear that two independent python processes creating tables in /tmp/tablite can contradict each other. This isn't acceptable at all.

Proposed changes:
- [ ] The pages will be stored using numpy's fileformat v.1 instead of HDF5.
- [ ] The HDF5 file is replaced with a working directory and processes will have the PID included in their sub-working directory.
- [ ] Tablite tables are considered volatile UNTIL saved explicitly by the user.

Branch:
The solution will be developed in the branch `hdf5_ectomy`.

---------

## Contents

1. Summary (above)
2. Numpy's fileformat
3. Workdir = path
5. Tables are volatile unless saved explicitly.
6. Multiprocessing / multiple mains in python

----------

## Numpy's fileformat.

Numpy's [NEP-1](https://numpy.org/neps/nep-0001-npy-format.html) presented a [simple file format](https://numpy.org/doc/stable/reference/generated/numpy.lib.format.html#module-numpy.lib.format) which roughly looks this:

```
\x93NUMPY\x03\x00\x00
{"descr":"<i8", "fortran_order":False,"shape":(3,3)}\n
\x05\x00\x00\x00\x00\x00\x00\x00
\x04\x00\x00\x00\x00\x00\x00\x00
\x07\x00\x00\x00\x00\x00\x00\x00
\x09\x00\x00\x00\x00\x00\x00\x00
\x01\x00\x00\x00\x00\x00\x00\x00
\x08\x00\x00\x00\x00\x00\x00\x00
\x03\x00\x00\x00\x00\x00\x00\x00
\x06\x00\x00\x00\x00\x00\x00\x00
\x02\x00\x00\x00\x00\x00\x00\x00
```

`\x93NUMPY` is the magix prefix
`\x03` is the major version of the numpy file format.
`\x00` is the minor version of the numpy file format.
`v\x00` (4 bytes form a little-endian unsigned int) is the padded length of the header modulo 64.
`{"descr":"<i8","fortran_order":False,"shape":(3,3)}\n` is the fileheader" with expected keys sorted in alphabetic order, ending with a `\n`-character. 
The remainder is the data in `UTF-8` encoding.

Read more in [numpy file format](https://numpy.org/doc/stable/reference/generated/numpy.lib.format.html#format-version-3-0)

## workdir = path 

In the `config.py` the working directory is set, which defaults to:

```
from tablite import Table
import tempdir
from pathlib import Path
import os
temp = path( tempdir.getTempDir() / f"tablite/{os.getpid()}" )
if not temp.exists():
    temp.mkdir()

Table.workdir = temp
```

Within the `workdir` the data is organised as follows:

```nim
/tmp/tablite/PID-14253/
    pages/
        p1b1.npy  # size set by settings.page_size
        p1b2.npy
        p2b2.npy
        p2b2.npy
        ...
        pNbN.npy
    page_index/  # linked list referring pages back to tables/
        1.yml 
        2.yml
        ...
    tables/
        1.yml
        2.yml
        ...
        N.yml
```

The `pages/` are all of the `npy` format, identifiable as `p<page number>b<block number>`. New pages are named using file from 1...int64max so that empty slots are tolerated.

The `page_index/` contains the equivalent of a linked list of pages pointing to tables.
```yaml
%YAML 1.2
filename: 1.yml
tables: [1,2,...]    
```

The `tables/` are all of the `yaml` format, identifiable by a numeric. The contents of a YAML file are illustrated below:

```yaml
%YAML 1.2                      yaml version
filename: 1.yml                reverse file identifier.
temp = false                   temp identifier.
columns:                       start of columns section.
    1:                         start of column 1.
        name: “列 1”           column name.
        pages: [p1b1, p1b2]    list of pages in column 1.
        types: []              empty list of types, so column 1 is a C-level data format.
    2:                         start of column 2.
        name: “列 2”           column name
        pages: [p2b1, p2b2]    list of pages in column 2.
        types: [p3b1, p3b2]    list of type codes, so column 2 is not a C-level data format.
```

tables and columns are mutable pointers to pages.
- pages immutable holders of data.
- data processing happens in functions using immutable npy pages [notes: 1, 2, 3].

For Tablite to know what is what, the user must register the function for the type code. In python this is done automatically using dtype or pickle. 

## Tablite tables are volatile UNTIL saved explicitly

Tablite data is considered volatile. This means that EVERY TIME a process shuts down, the `workdir` for the PID is erased (`sigint` - a part of `__exit__`). 
If the process is `sigkill`'ed the data will remain idle until the PID is used again, whereby the process will erased the contents of the PID-specific folder. There is no other way.

Due to Tablites focus on larger-than-memory datasets, Tablite must write to disk. To assure that we won't run out of disk space, the function that writes will use a `disk_limit=0.90` and complaint if the disk usage exceeds 90%.

During multiprocessing, Tablite will share the working directory with the sub-processes in a parent/child-type hierarchy, so that subprocesses won't scatter data in various random folders.

### save

With `tmp/tablite/<PID>/...` as the working director a simple starting point for PERSISTENT usage of data would look like this:

1. Import data (this uses working dir) with the usual `t = Table.import(/my/docs/originals/somefile.csv)`
2. Save data using `table.save()` to your preferred folder, such as `/my/docs/wip/data.npz` which is a portable zip'ed folder of the table from the working directory. THIS FILE WILL NEVER BE ERASED BY TABLITE.
3. Load your table using `t = Table.load("/my/docs/wip/data.npz")`, which drops the imported table in the working directory and uses the `.npz` instead - which now is tablite & numpy native.

Thereby, if you are having a large test suite, you may avoid the reimport of datasets completely. Any subsequent work that uses `t` will still happen in the working directory under the PID.

The reason is that `t.save(...)` creates an isolated portable snapshot of the table's data, whilst setting `T.workdir = ...` uses paginated linking, which is far more space efficient and hence faster.

## Multiprocessing / multiple python processes.

When `tasks` are created by `main` it must declare the destination folder in the task, so that when a new subprocess starts, they will know which process' folder to write to.  This guarantees that there will be no conflict when two Python processes use tablite concurrently.
